### ISSUE TITLE
测试性能与论文不符合

### ISSUE THREAD

**Issue by LimFang** [Frank-Wang-oss/FCSTGNN#12]
您好，这是一个很棒的工作！我们在C-MAPSS数据集上进行了测试该网络，但是在四个子集中达不到论文的数据 ，是不是需要有别的设置呢？很期待您的回复！

**Comment by Frank-Wang-oss** [comment]
Some hyper parameters can largely affect the performance, especially patch size. Another point is that we did not fix the training seed, so it is normal to get different results. We have benchmarking which also includes this method and has fixed seeds, which can achieve even better performance in FD002 to FD004. The benchmarking codes will be released soon.
